#!/bin/bash

SNAPSHOT_HASH=$(cat SNAPSHOT_HASH)
ROOT_DIR=`pwd`
sudo apt-get update
sudo apt-get install git git-man git-svn  wget curl software-properties-common unzip  python3 python-is-python3 lsb-release apt-transport-https -y
DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install tzdata
pip3 install wheel
pip3 install .
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
git clone https://github.com/flutter/engine.git
cd $ROOT_DIR
export PATH=$PATH:$ROOT_DIR/depot_tools
cd engine
git config --global user.email "reflutter@example.com" && git config --global user.name "reflutter"
git fetch origin $(reflutter "$SNAPSHOT_HASH" -l)
git reset --hard FETCH_HEAD
reflutter "$SNAPSHOT_HASH" -l
echo 'reflutter' > REFLUTTER
git add . && git commit -am "reflutter"
cd $ROOT_DIR
mkdir --parents customEngine
cd customEngine
echo 'solutions = [{"managed": False,"name": "src/flutter","url": "'$ROOT_DIR/engine'","custom_deps": {},"deps_file": "DEPS","safesync_url": "",},]' > .gclient
gclient sync
reflutter "$SNAPSHOT_HASH" -l
cd $ROOT_DIR
sudo customEngine/src/build/install-build-deps-android.sh --no-prompt
cd $ROOT_DIR
export PATH=$PATH:`pwd`/depot_tools && customEngine/src/flutter/tools/gn --android --android-cpu=arm64 --runtime-mode=release && ninja -C customEngine/src/out/android_release_arm64
cd $ROOT_DIR
export PATH=$PATH:`pwd`/depot_tools && customEngine/src/flutter/tools/gn --android --android-cpu=arm --runtime-mode=release && ninja -C customEngine/src/out/android_release
cd $ROOT_DIR
cp customEngine/src/out/android_release_arm64/lib.stripped/libflutter.so libflutter_arm64.so 2>/dev/null
cp customEngine/src/out/android_release/lib.stripped/libflutter.so libflutter_arm.so 2>/dev/null
cp customEngine/src/out/android_release_x64/lib.stripped/libflutter.so libflutter_x64.so 2>/dev/null
cp customEngine/src/out/android_jit_release_x86/lib.stripped/libflutter.so libflutter_x86.so 2>/dev/null
