#!/usr/bin/env python3
"""
Generate disassembler scripts from a reFlutter dump.dart (JSONL: one object
per function with method_name / offset / library_url / class_name).

Outputs, next to dump.dart:
  dump_ida.py      - IDA python: name every function at libapp.so+offset
  dump_ghidra.py   - Ghidra Jython: same for the Ghidra script console

The offsets are relative to the Dart instructions image start
(_kDartSnapshotText / _kDartIsolateSnapshotInstructions) - see README.
"""

import json
import os
import sys


def load_entries(path):
    entries = []
    with open(path, "r", errors="replace") as f:
        # the dump is one JSON object per line (no newlines inside objects)
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                # tolerate concatenated objects on one line, skip corrupt ones
                try:
                    decoder = json.JSONDecoder()
                    idx = 0
                    while idx < len(line):
                        obj, end = decoder.raw_decode(line, idx)
                        entries.append(obj)
                        idx = end
                        while idx < len(line) and line[idx] not in "{":
                            idx += 1
                except json.JSONDecodeError:
                    import sys
                    print("[!] skipping corrupt line: {}...".format(line[:60]), file=sys.stderr)
                continue
            entries.append(obj)
    return entries


def safe_name(entry, seen):
    base = "{}${}.{}".format(
        entry.get("class_name", ""),
        entry.get("method_name", "<anon>"),
        entry.get("library_url", "").rsplit("/", 1)[-1].replace(".dart", ""),
    )
    name = "".join(c if c.isalnum() or c in "_$" else "_" for c in base)[:200]
    while name in seen:
        name += "_"
    seen.add(name)
    return name


def main():
    if len(sys.argv) != 2:
        print("Usage: {} dump.dart".format(sys.argv[0]))
        sys.exit(1)
    dump_path = sys.argv[1]
    entries = load_entries(dump_path)
    seen = set()
    pairs = [(entry["offset"], safe_name(entry, seen)) for entry in entries if "offset" in entry]

    ida = os.path.join(os.path.dirname(dump_path) or ".", "dump_ida.py")
    with open(ida, "w") as f:
        f.write("# generated by dump2disasm.py - run inside IDA with libapp.so loaded\n")
        f.write("# NOTE: offsets are from the Dart instructions image start\n")
        f.write("# (_kDartIsolateSnapshotInstructions / _kDartSnapshotText),\n")
        f.write("# NOT from the ELF base - resolve that symbol first\n")
        f.write("import idaapi, idc\n")
        f.write("# resolve the instructions-image symbol for correct addresses\n")
        f.write("# falls back to ELF base for legacy module-relative offsets\n")
        f.write("sym = idc.get_name_ea_simple('_kDartSnapshotText')\n")
        f.write("if sym == idc.BADADDR:\n")
        f.write("    sym = idc.get_name_ea_simple('_kDartIsolateSnapshotInstructions')\n")
        f.write("if sym == idc.BADADDR:\n")
        f.write("    print('WARNING: symbol not found, using ELF base - offsets may be wrong')\n")
        f.write("    sym = idaapi.get_imagebase()\n")
        f.write("base = sym\n")
        f.write("symbols = {\n")
        for offset, name in pairs:
            f.write("    {}: '{}',\n".format(offset, name))
        f.write("}\n")
        f.write("for off, name in symbols.items():\n")
        f.write("    idc.set_name(base + int(off, 16) if isinstance(off, str) else base + off, name)\n")
        f.write("print('named {} functions'.format(len(symbols)))\n")

    ghidra = os.path.join(os.path.dirname(dump_path) or ".", "dump_ghidra.py")
    with open(ghidra, "w") as f:
        f.write("# generated by dump2disasm.py - run in Ghidra's Script Manager\n")
        f.write("# with libapp.so analyzed; offsets are from the Dart instructions image\n")
        f.write("from ghidra.program.model.symbol import SourceType\n")
        f.write("fm = currentProgram.getFunctionManager()\n")
        f.write("image = toAddr(0)  # adjust: base of _kDartSnapshotText section\n")
        f.write("count = 0\n")
        for offset, name in pairs:
            f.write(
                "createFunction(image.add({}), '{}'); count += 1\n".format(
                    int(offset, 16) if isinstance(offset, str) else offset, name
                )
            )
        f.write("print('named {} functions'.format(count))\n")

    print("[+] {} entries -> {} and {}".format(len(pairs), ida, ghidra))


if __name__ == "__main__":
    main()
